Repository Ducky-Chickens/bangazonCLI, pull requests merged in 2018-04, with the labels that each got.

#16 Tac jsdoc
  app/activeCustomer.js
  out/activeCustomer.js.html
  out/fonts/OpenSans-Bold-webfont.eot
  out/fonts/OpenSans-Bold-webfont.svg
  out/fonts/OpenSans-Bold-webfont.woff
  out/fonts/OpenSans-BoldItalic-webfont.eot
  out/fonts/OpenSans-BoldItalic-webfont.svg
  out/fonts/OpenSans-BoldItalic-webfont.woff
  out/fonts/OpenSans-Italic-webfont.eot
  out/fonts/OpenSans-Italic-webfont.svg
  out/fonts/OpenSans-Italic-webfont.woff
  out/fonts/OpenSans-Light-webfont.eot
  out/fonts/OpenSans-Light-webfont.svg
  out/fonts/OpenSans-Light-webfont.woff
  out/fonts/OpenSans-LightItalic-webfont.eot
  out/fonts/OpenSans-LightItalic-webfont.svg
  out/fonts/OpenSans-LightItalic-webfont.woff
  out/fonts/OpenSans-Regular-webfont.eot
  out/fonts/OpenSans-Regular-webfont.svg
  out/fonts/OpenSans-Regular-webfont.woff
  out/global.html
  out/index.html
  out/scripts/linenumber.js
  out/scripts/prettify/Apache-License-2.0.txt
  out/scripts/prettify/lang-css.js
  out/scripts/prettify/prettify.js
  out/styles/jsdoc-default.css
  out/styles/prettify-jsdoc.css
  out/styles/prettify-tomorrow.css
  package.json
Labels: enhancement

#22 migrated data from ducky chickens API
  data/customers.js
  data/orderProducts.js
  data/orders.js
  data/paymentTypes.js
  data/productTypes.js
  data/products.js
  package-lock.json
Labels: enhancement

#27 updated data to match required parameters for CLI
  data/orderProducts.js
  data/orders.js
  data/paymentTypes.js
  data/products.js
Labels: requirement

#29 Tac select active customer
  .gitignore
  app/activeCustomer.js
  app/controllers/activateCustomerCtrl.js
  app/models/Customer.js
  app/models/getCustomers.js
  app/ui.js
  out/activeCustomer.js.html
  out/fonts/OpenSans-Bold-webfont.eot
  out/fonts/OpenSans-Bold-webfont.svg
  out/fonts/OpenSans-Bold-webfont.woff
  out/fonts/OpenSans-BoldItalic-webfont.eot
  out/fonts/OpenSans-BoldItalic-webfont.svg
  out/fonts/OpenSans-BoldItalic-webfont.woff
  out/fonts/OpenSans-Italic-webfont.eot
  out/fonts/OpenSans-Italic-webfont.svg
  out/fonts/OpenSans-Italic-webfont.woff
  out/fonts/OpenSans-Light-webfont.eot
  out/fonts/OpenSans-Light-webfont.svg
  out/fonts/OpenSans-Light-webfont.woff
  out/fonts/OpenSans-LightItalic-webfont.eot
  out/fonts/OpenSans-LightItalic-webfont.svg
  out/fonts/OpenSans-LightItalic-webfont.woff
  out/fonts/OpenSans-Regular-webfont.eot
  out/fonts/OpenSans-Regular-webfont.svg
  out/fonts/OpenSans-Regular-webfont.woff
  out/global.html
  out/index.html
  out/scripts/linenumber.js
  out/scripts/prettify/Apache-License-2.0.txt
  out/scripts/prettify/lang-css.js
  out/scripts/prettify/prettify.js
  out/styles/jsdoc-default.css
  out/styles/prettify-jsdoc.css
  out/styles/prettify-tomorrow.css
  test/activeCustomer.test.js
Labels: requirement

#30 Display Current Customer & Fix Select Customer
  app/activeCustomer.js
  app/controllers/activateCustomerCtrl.js
  app/ui.js
  test/activeCustomer.test.js
Labels: requirement

#34 View Stale Products
  app/controllers/pressEnterToContinue.js
  app/models/GetStaleProducts.js
  app/models/sql/selectStaleProductsSql.js
  app/ui.js
  data/orders.js
  package-lock.json
  package.json
  test/customer.test.js
  test/getStaleProducts.test.js
Labels: requirement

#35 Hp update product
  app/controllers/addPaymentTypeCtrl.js
  app/controllers/updateProductCtrl.js
  app/models/AddPaymentType.js
  app/models/UpdateProduct.js
  app/ui.js
  test/addCustomerProduct.test.js
  test/addPaymentType.test.js
  test/updateProduct.test.js
Labels: requirement

#37 fixed broken require statement crashing application
  app/ui.js
Labels: bug

#36 Allow a user to complete a customers order
  app/controllers/activateCustomerCtrl.js
  app/controllers/completeOrderCtrl.js
  app/models/CompleteOrder.js
  app/ui.js
  data/orders.js
  data/paymentTypes.js
  data/products.js
  test/completeOrder.test.js
Labels: requirement

#44 Abstract stale products and activate customer
  app/controllers/activeCustomerCtrl.js
  app/controllers/staleProductsCtrl.js
  app/helpers/addSpace.js
  app/ui.js
Labels: enhancement

#41 Add quantity updating and fix complete order tests
  app/controllers/completeOrderCtrl.js
  app/models/CompleteOrder.js
  app/ui.js
  data/orders.js
  test/addOrderProduct.test.js
  test/completeOrder.test.js
Labels: bug, enhancement

#46 removed order test skup and added product value column to testing
  test/completeOrder.test.js
Labels: enhancement

#48 Stale Product Tests
  app/models/AddCustomerProduct.js
  test/getStaleProducts.test.js
Labels: requirement

#50 Readme Outline
  README.md
Labels: requirement

#51 Tm customer revenue
  README.md
  app/controllers/addCustomerProductCtrl.js
  app/controllers/getCustomerRevenueCtrl.js
  app/models/GetCustomerRevenue.js
  app/ui.js
  test/completeOrder.test.js
  test/getCustomerRevenue.test.js
  test/getStaleProducts.test.js
Labels: requirement

#49 updated complete order readme section
  README.md
Labels: requirement

#57 Remove console.table and change to use cliui.
  app/ui.js
Labels: requirement

#56 Add stale and popular product example output.
  README.md
Labels: requirement
